### ISSUE TITLE
Can't  run Example

### ISSUE THREAD

**Issue by isakvan** [FolioReader/FolioReaderKit#174]
I ran  - $ pod install   from Example dir, I tried from root too.
What I do wrong? Thank you.
And Get this report:

Setting up CocoaPods master repo

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

Setup completed
Analyzing dependencies
Fetching podspec for `FolioReaderKit` from `../`
[!] No podspec found for `FolioReaderKit` in `../`
isaks-MacBook-Air:Example isakvainshtein$ pod install
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:173:in `chdir': No such file or directory - getcwd (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:173:in `block in repo_information'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:170:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:170:in `repo_information'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:24:in `report'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:64:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

**Comment by isakvan** [comment]
Ok, works, thanks
